### ISSUE TITLE
glue:::delayed_assign uses CRAN-illegal .Internal()

### ISSUE THREAD

**Issue by BillDunlap** [tidyverse/glue#101]
glue:::delayed_assign(x, value) does not delay evaluation of value like base:delayedAssign does and it uses CRAN-illegal .Interal() to implement it. 

To see the non-delayed evaluation:
> packageVersion("glue")
[1] ‘1.3.0’
> glue:::delayed_assign("XXX", { cat("Making XXX now\n") ; 1:7 })
Making XXX now
>
> base::delayedAssign("YYY", { cat("Making YYY now\n") ; 1:7 })
> log(YYY)
Making YYY now
[1] 0.0000000 0.6931472 1.0986123 1.3862944 1.6094379 1.7917595 1.9459101

The CRAN-illegal .Internal call is hidden to avoid the CRAN checks:

> glue:::delayed_assign
function (x, value, eval.env = parent.frame(1), assign.env = parent.frame(1))
{
    (get(".Internal", baseenv()))(delayedAssign(x, value, eval.env,
        assign.env))
}
<bytecode: 0x28766b8>
<environment: namespace:glue>

This is an internal-to-package function so I am not sure what it is supposed to do.

**Comment by msannell** [comment]
Looking at the comments in glue's R code, I figured out that Bill (my
co-worker) had missed the point that glue:::delayed_assign was
designed so that the 'value' argument would be evaluated like a normal
argument, rather than substituted.  Thus, passing 'value' as a quoted
expression produces the expected result:

    > glue:::delayed_assign("XXX", quote({ cat("Making XXX now\n") ; 1:7 }))
    > XXX
    Making XXX now
    [1] 1 2 3 4 5 6 7
    >

In any case, his complaint that you shouldn't call .Internal is still
valid.  A better way to get the behavior you want is to pass
delayedAssign to do.call, as so:

    > xx <- function(x, value, eval.env = parent.frame(1), assign.env = parent.frame(1)) {
    +   do.call(base::delayedAssign, list(x, value, eval.env, assign.env))
    + }
    > xx("XXX",quote({ cat("Making XXX now\n") ; 1:7 }))
    > XXX
    Making XXX now
    [1] 1 2 3 4 5 6 7
    >

**Comment by jimhester** [comment]
Thank you to you both, should now be fixed via `do.call()` as suggested by @msannel. I assume the previous behavior caused an issue with TERR?

**Comment by msannell** [comment]
Yes, this previous implementation caused an issue with TERR.  TERR
implements .Internal to handle a fixed set of functions, in order to
handle old packages that (incorrectly) make calls to .Internal.
delayedAssign was not one of the functions handled, so a number of
glue's testthat tests failed with an error "unimplemented .Internal
function: delayedAssign".  To fix this, I just added an implementation
of delayedAssign to TERR's .Internal.  In any case, it is a good thing
to change your implementation of glue:::delayed_assign.

**Comment by jimhester** [comment]
Makes sense, will keep this in mind for the future, thanks for the explanation!

**Comment by egnha** [comment]
A side remark about the forcing “trick” via `do.call()`, which I learned from some code by Martin Maechler (though I don't recall where I saw it, originally): It's quite useful for avoiding hairy invocations like
```R
expr <- quote(a + b)

eval(substitute(substitute(X, list(a = 1)), list(X = expr)))
#> 1 + b
```
(Alternatively, one could use `bquote()`—but it's going through more less the same circumlocution.) Despite having seen this sort of code many times, I still find it maddening. Instead, you can write
```R
do.call(substitute, list(expr, list(a = 1)))
#> 1 + b
```
which is much clearer.
