### ISSUE TITLE
feature request: glue for formulas

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/glue#108]
Building dynamic formulas is painful, The equivalent of the following would be nice in the `glue` package.

```
glue.default <- glue::glue

glue <- function(...) UseMethod("glue")

glue.formula <- function(.formula, .envir = parent.frame(), ...){
  formula_chr <- gsub("\\n\\s*","",as.character(.formula)[c(2,1,3)])
  args <- c(as.list(formula_chr), .sep=" ", .envir = .envir)
  as.formula(do.call(glue::glue, args),env = .envir)
}

var <- "x"
formula <- y ~ poly({var}, 2)
glue(formula)
# y ~ poly(x, 2)
```

**Comment by lionel-** [comment]
I'm not sure about the status of `expr_interp()` in the API. I think it will be supersceded by `bang()`.

**Comment by lionel-** [comment]
@moodymudskipper In the mean time you can also do it like this:

```r
var <- sym("x")
eval(expr(y ~ poly(!!var, 2))
```

This is fundamentally equivalent to glue interpolation except that since you're working with expressions you need to disambiguate between strings and symbols by transforming strings to symbols explicitly with `sym()` or `syms()`. This slight inconvenience is rewarding because it will give you robustness. See https://community.rstudio.com/t/tidy-evaluation-and-formulae/4561/12 for an example of the robustness.

**Comment by moodymudskipper** [comment]
Many thanks for your answers, these will come in handy for sure.

My glue code might be suboptimal but I still think that such interface would be useful.

Just today I did a lot of interactive tweaking and the function I wrote above really helped, consider the following examples, where `vars` is either a function's arguments, or names I play around with interactively, because I run a handful of models on them, using `vars` to save typing and avoid mistakes : 

```
vars <- c("Sepal.Width","Sepal.Length")

# my desired output
formula1 <- Sepal.Width ~ Sepal.Length
summary(lm(formula1, iris))$r.squared 
# [1] 0.01382265

# the brute solution:
x <- iris[[vars[1]]]
y <- iris[[vars[2]]]
formula2 <- x~y # different formula though
summary(lm(formula2,iris))$r.squared
# [1] 0.01382265

# glue solution
formula3 <- glue({vars[1]} ~ {vars[2]})
summary(lm(formula3, iris))$r.squared 
# [1] 0.01382265

# tidyeval solution
vars_ <- syms(vars)
formula4 <-  eval(expr(!!vars_[[1]] ~ !!vars_ [[2]]))
summary(lm(formula4,iris))$r.squared
# [1] 0.01382265
```
The tidy eval is twice more verbose and will scare my coworkers, and I need to define the extra variable and remember the structure.

Here I took another shot at it to simplify:

```
subform <- function(formula, ...){
  args <- syms(list(...))
  subst_ <- substitute(
    substitute(formula, args),
    list(formula = formula))
  as.formula(eval(subst_),attr(formula,".Environment"))
}

formula5 <- subform(x ~ y,  x = vars[1],  y = vars[2])
summary(lm(formula5,iris))$r.squared
# [1] 0.01382265
```

That's not too bad and reminds me of `sprintf`, could be more readable than the glue option depending on the case (not sure where it would fit in the `tidyverse` though. I think it would be possible to design a variant to be able to call `subform(..1 ~ ..2, vars)` but I didn't succeed.

The problem with the bang bang interface is that we can't start from the formula, we need to use `sym` first, and for interactive use I don't find it satisfying, the glue interface, conceptual problems aside, is really convenient on the other hand as all I need is contained in the formula and the local environment. 

`reformulate` works with character inputs, `update.formula` feels a lot like using `glue`, so is it such a big philosophical stretch to make glue handle formulas ?

**Comment by egnha** [comment]
@moodymudskipper, your base R solution looks to solve your problem nicely. Here are a few points you might also want to consider:

- It is more idiomatic to write `environment(fml)` rather than `attr(fml, ".Environment")`.
- Symbol substitution can be more transparently done using `do.call(substitute, list(formula, args))`. (This is not obvious!)
- @lionel- alluded to this: Are you sure you want to input symbols as strings? How would you distinguish bona fide strings from strings-meant-as-symbols? Consider `rlang::exprs()` in place of `syms(list(...))`.

As for `glue()`, if it were extended it to handle formulas, it would no longer return a consistent type. Generally, that would make `glue()` trickier to reason about in programs—you'd have to follow the chain of calls leading to it to know its return type. Is that a good tradeoff?

**Comment by moodymudskipper** [comment]
So much value here (and great questions too)! Thanks so much for taking the time.

I use strings in part because:
* I'm more comfortable with them (as you could see I haven't wrapped my head around all the tidyselect concepts and function)
 * I "feel" that symbols are for programming and that good old strings make more sense for analysis, which might not be the best reason :)
* I may need to share my code, and I am slowly winning ground in my daily SAS vs R battle, I don't want to turn off co-workers with advanced concepts
* in my use case of yesterday I was creating columns such as `x_new`, easier to do when my raw material is `character`.

You make an excellent point about type stability, it went over my head because my `glue` calls are always fairly simple. What about `glue_formula` then ?

**Comment by moodymudskipper** [comment]
@egnha Your suggestions concerning `substitute` and `environment` worked beautifully, here is my modified code

```
subform <- function(formula, ...){
  args <- syms(list(...))
  subst_ <- do.call(substitute, list(formula, args))
  as.formula(eval(subst_), environment(formula))
}
```
@Lionel I trust that you and your team will make the right decisions, thanks for the great insights and letting me present my case.

**Comment by egnha** [comment]
@moodymudskipper, an oversight, perhaps?: once `subst_` is assigned, I'd presume you don't want to evaluate it in the body of the function, otherwise its environment will be fixed there, rather than set to the environment of `formula` (cf. implementation of `as.formula()`); that is, it looks like you want to drop the `eval()`.

**Comment by topepo** [comment]
@lionel- I don't have anything in `recipes` that would solve this.

**Comment by moodymudskipper** [comment]
@egnha indeed, updated thanks!

**Comment by JohnMount** [comment]
stats::reformulate() ?

**Comment by hadley** [comment]
This definitely shouldn't be a glue function; we don't want to encourage code generation with strings.
