### ISSUE TITLE
Why `.con` is mandatory in `glue_sql()` for character ?

### ISSUE THREAD

**Issue by philibe** [tidyverse/glue#120]
Hello,

For numeric parameters this query works:

    glue_sql ("WHERE id IN ({param*})",param=c(1,2))
       -> WHERE id IN (1, 2)

For character parameters this query doesn't works:

    glue_sql ("WHERE name IN ({param*})",param=c("A","B"))
        -> Error in sql_quote_transformer(.con) : 
            argument ".con" is missing, with no default

But with `.con` character parameters this query works:

    connexion_bdd= DBI::dbConnect(odbc::odbc(),.connection_string=connexion_bdd_odbc_txt)
    glue_sql ("WHERE name IN ({param*})",param=c("A","B"),.con=connexion_bdd)
       -> WHERE name IN ('A', 'B')

I don't understand why `.con` is mandatory  for character parameters :) Or is it in fact mandatory for all type of queries ? 
I use `glue_sql()` only for parametrized queries but you make `glue_sql()` also to prevent injection and you need the connection for that ?

I omit `.con` because it was strange for me to call the connection not only in `DBI::dbGetQuery` but also for construction of the SQL (in `glue_sql()`)

**Comment by yutannihilation** [comment]
Since you need to escape characters and the way of escaping depend on the DB (e.g. `don't` might be escaped to `don''t` or `don\'t`), `glue_sql()` needs to call `DBI::dbQuoteString()`, which requires the connection.

https://github.com/tidyverse/glue/blob/ea29e09fc6f685c9d7c33068e5017c1c14544c46/R/sql.R#L130-L132

Also, variable names needs to be quoted (e.g. `" "` or `` ` ` ``), which `DBI::dbQuoteIdentifier()` does for you.

That's why `.con` is required. If you don't care about the details of quotation, `DBI::ANSI()` might be a choice as a dummy connection.

``` r
glue::glue_sql("WHERE name IN {param*}", param=c("A","B"), .con = DBI::ANSI())
#> <SQL> WHERE name IN 'A', 'B'
```

<sup>Created on 2019-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Maybe, when `.con` is missing, `glue_sql()` could fall back to `DBI::ANSI()` with a warning?

**Comment by philibe** [comment]
Thank you for this explanation :)
