### ISSUE TITLE
Safe version of glue

### ISSUE THREAD

**Issue by jimhester** [tidyverse/glue#140]
It would be useful to have a safe version of glue that did not evaluate arguments, only looked them up with `get()`. This way glue could be used in shiny apps and similar places without concern. It is of course possible to do this already with a custom transformer, but it seems a common enough case we should probably have a new function for it.

**Comment by jcheng5** [comment]
@rich-iannone and I ended up needing something like this for a package that needs "safe glue" in a bunch of places, and discovered that `.transformer = base::get` actually works nicely!

However, I totally agree that a first-class glue function that works this way would be fantastic--the idea that people might be using regular `glue::glue` with Shiny is terrifying!

**Comment by jimhester** [comment]
I didn't realize the `pos` argument to `get()` also takes environments, so yeah `.transformer = base::get` seems the solution. I also didn't see this response until after posting my reply in the other thread, apologies for telling you something you had already done!

**Comment by jimhester** [comment]
I will add a `glue_safe()` function using `get()` in the next CRAN release of glue.

**Comment by jcheng5** [comment]
Along similar lines, can I also request for `glue_data` to treat `envir = NULL` like `envir = emptyenv()`? (Not sure what you'd want to do with `glue(envir = NULL)`.)

Because the other "gotcha" we've had with glue for package development is intending to operate on user data (i.e. `glue_data(.x = ...)`) but accidentally including local/lexical scope (i.e. the variables belonging to the package).

**Comment by jimhester** [comment]
Closed by https://github.com/tidyverse/glue/commit/46a3ee3700f39ef1588d55800aed40a361a34211
