### ISSUE TITLE
new line removed when line ends with "\"

### ISSUE THREAD

**Issue by svdwoude** [tidyverse/glue#161]
If we have the following text

```
line one
line two ending with \
last line
```
 and would like to use `glue` on it, it will remove the new line character and `\` character on line 2.
I would not expect `glue` to alter the formatting of the input text.

reprex:

```r
library(magrittr)
text <- "line one\nline two ending with \\\nlast line"
text %>% 
  glue::glue() %>% 
  as.character()
#> [1] "line one\nline two ending with last line"
```
current workaround:

``` r
library(magrittr)
text <- "line one\nline two ending with \\\nlast line"
text %>% 
  # add space between "\" and "\n" character
  stringr::str_replace_all("\\\\\\n","\\\\ \n") %>% 
  glue::glue() %>% 
  # remove space between "\" and "\n" character
  stringr::str_replace_all("\\\\ \\n", "\\\\\n") %>% 
  as.character()
#> [1] "line one\nline two ending with \\\nlast line"
```

**Comment by cderv** [comment]
I think this is because `glue::glue` uses `glue::trim` by default. You just need to set `.trim = FALSE` and you get the expected result. Continuous line across newlines by using `\` is one of the feature supported. See `?glue::trim`
``` r
library(magrittr)
text <- "line one\nline two ending with \\\nlast line"
text %>% 
  glue::glue(.trim = FALSE) %>% 
  as.character()
#> [1] "line one\nline two ending with \\\nlast line"

glue::trim(text)
#> [1] "line one\nline two ending with last line"
```

<sup>Created on 2019-12-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Hope it helps.

**Comment by svdwoude** [comment]
Thanks @cderv! 
I somehow overlooked the `.trim` argument.
