### ISSUE TITLE
`Rf_` and `R_` functions without #define R_NO_REMAP, how come?

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/glue#184]
This is neither a bug report nor a feature request, just a simple question really.

How did you manage to use the R's C API  functions with the prefixes `Rf_` or `R_` without (seemingly) `#define R_NO_REMAP`?

For example, here: https://github.com/tidyverse/glue/blob/7775b0fbb5f572d3cf8240c239ebde0b1e3a19e1/src/glue.c#L1-L13

you use both `Rf_xlength` and `Rf_lengthgets`. Just wondering really. I am trying to learn the C API and [Adv-R 1st edition book](http://adv-r.had.co.nz/C-interface.html) says:

> All functions are defined with either the prefix Rf_ or R_ but are exported without it (unless #define R_NO_REMAP has been used).

**Comment by ramiromagno** [comment]
Now that we are at this piece code, just out of curiosity, why do you duplicate the vector length at line 8, and not simply increasing the length just enough to include the ith `val`?

**Comment by jimhester** [comment]
The book is incorrect, the `Rf_` prefix functions are always available, the versions with `Rf_` _absent_ are only defined if `R_NO_REMAP` is not defined, see the code from the relevant header https://github.com/wch/r-source/blob/fee68fa94b6586bd2e257c0993cd79c4258a0876/src/include/Rinternals.h#L1505.

But we should probably still define `R_NO_RMAP` here anyway.

We use a growth factor of 2 so that repeated appends grow at O(1) amortized time rather than O(n). e.g. you don't have to copy the elements every time you append, only when the length exceeds the current length (which doubles each time it grows).

These sorts of questions are a better fit for <https://community.rstudio.com>. In the future do you mind asking them over there?

**Comment by ramiromagno** [comment]
Thanks a lot!
