### ISSUE TITLE
glue_sql converts length-0 vectors to NULL in asterisk-expansion

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/glue#272]
```R
x <- character(0)
glue::glue_sql("{x*}")
# <SQL> NULL
```
When used as part of an SQL expression, this can happen:
```R
glue::glue_sql("select foo from bar where baz in ({x*})")
# <SQL> select foo from bar where baz in (NULL)
```
... which has different semantics (in most SQL variants) than what I believe most users likely are intending when `x` is empty:
```R
# <SQL> select foo from bar where baz in ()  <-- the _intended_ SQL, I think.
```

I've confirmed this also happens with DB object identified expansion, too, i.e.:
```R
"{`x`*}"
# <SQL> NULL
```

**Comment by hadley** [comment]
``` r
x <- character(0)
glue::glue_sql("({x*})")
#> <SQL> (NULL)
```

<sup>Created on 2023-01-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jasonheffnerpsu** [comment]
Post upgrade to glue version 1.7.0, we encountered a breaking change in how glue_sql handles empty vectors. Previously, empty vectors were collapsed to "NULL" in SQL queries, which was functional for our use case. However, since the update, empty vectors are now collapsed to an empty string, resulting in syntax errors in SQL queries with IN clauses.

This change impacts all database queries where we dynamically generate IN clauses based on possibly empty vectors. The new behavior leads to malformed SQL queries and runtime errors, significantly affecting our data retrieval processes.

Could we consider reintroducing the previous behavior of collapsing empty vectors to "NULL" in SQL queries, or provide an option to toggle between the two behaviors? This would allow for backward compatibility and flexibility for different use cases.

We've implemented a workaround where we manually check for empty vectors and adjust the SQL query accordingly. However, this adds complexity and boilerplate code, which was elegantly handled by glue_sql in previous versions.

**Comment by hadley** [comment]
@jasonheffnerpsu can you please file an new issue instead of commenting on a closed issue?

**Comment by jasonheffnerpsu** [comment]
Apologies .. I don't raise issues often and don't know process

**Comment by peterdesmet** [comment]
I am encountering similar issues when using glue 1.7.0 (https://github.com/inbo/movepub/issues/59).

Before (glue 1.6.0) I could pass a parameter/variable `rights_holder` with value `NULL` to `glue_sql()` and it would be interpreted as `NULL`.

``` r
library(glue)
library(DBI)
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
rights_holder <- NULL
sql <- "SELECT {rights_holder} AS rights_holder, * FROM data"
glue(sql)
glue_sql(sql, .con = con)
#> <SQL> SELECT NULL AS rights_holder, * FROM data
```

<sup>Created on 2024-01-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Now (glue 1.7.0), the result of `glue_sql()` is an empty `<SQL>` class. `glue()` does not return anything:

``` r
library(glue)
library(DBI)
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
rights_holder <- NULL
sql <- "SELECT {rights_holder} AS rights_holder, * FROM data"
glue(sql)
glue_sql(sql, .con = con)
#> <SQL>
```

<sup>Created on 2024-01-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by peterdesmet** [comment]
Sorry, did the same (commenting on a closed PR). I will report my use case at #318.
