### ISSUE TITLE
"glue" class of the result from glue() prevents recycling

### ISSUE THREAD

**Issue by marioem** [tidyverse/glue#299]
Value returned from a call to `glue` inherits "glue" class which seems to prevent R from recycling that value where necessary.

``` r
model_name <- "kNN"
data.frame(num = 1:10, label = glue::glue("{model_name} label"))
#> Error in data.frame(num = 1:10, label = glue::glue("{model_name} label")): arguments imply differing number of rows: 10, 1
```
<sup>Created on 2023-02-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>```

This shows up in following real world code:

```
model_name1 <- str_split(str_replace(bestWf1, "_", " "), " ")[[1]][2]

explainer_ds1 <- 
  explain_tidymodels(
    last_wf_fit1, 
    data = vip_train1, 
    y = train_datas1 %>% pull(!!dv),
    label = glue::glue("{model_name1} model, DS1"), 
    verbose = F
  )
```

There is a number of possible workarounds, like `%>% cat()`, `%>% as.character()` but maybe something more elegant could be devised in `glue()` itself.

**Comment by jennybc** [comment]
``` r
data.frame(x = 1:2, y = "hmmm")
#>   x    y
#> 1 1 hmmm
#> 2 2 hmmm
data.frame(x = 1:2, y = glue::as_glue("hmmm"))
#> Error in data.frame(x = 1:2, y = glue::as_glue("hmmm")): arguments imply differing number of rows: 2, 1
```

<sup>Created on 2023-09-22 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
I don't know of anything elegant that glue can do. `data.frame()` generally does not recycle objects with a class. There are special case arrangements for `factor`, `Date`, `POSICxt`, and character marked with `'AsIs'` (the `I()` case you see above):

https://github.com/wch/r-source/blob/74bec15fc57b1b6f2ad4c312ae401200d4ff84ed/src/library/base/R/dataframe.R#L525-L536

Otherwise, `data.frame()` throws the error you're seeing.

I think your options are:

* Explicitly strip the glue class
* Explicitly apply the `'AsIs'` class
* Make a tibble instead of a plain data.frame
* 
gluething <- glue::as_glue("hmmm")

data.frame(x = 1:2, y = gluething)

data.frame(x = 1:2, y = as.character(gluething))

data.frame(x = 1:2, y = I(gluething))

tibble::tibble(x = 1:2, y = gluething)
