### ISSUE TITLE
`glue_data()` throw error with regex pattern to for space

### ISSUE THREAD

**Issue by Eliford** [tidyverse/glue#304]
The following use of glue_data fails as follows
```r
glue('My name is {str_extract("Jane, John", "(?=\\s).+")}')
```
Error: '\s' is an unrecognized escape in character string starting ""(?=\s"

**Comment by PettyCode** [comment]
The error you're seeing is due to the way that R interprets backslashes (\) in strings. In R, the backslash is an escape character, which means it's used to introduce special character sequences. For instance, \n is a newline, and \t is a tab.

In your case, you want to include a literal backslash in your string because \\s is part of a regular expression. But to do this in R, you need to escape the backslash itself, which requires doubling it. This is why you often see regular expressions in R with double backslashes, like \\s for a space.

However, because the regular expression is inside a string that's already inside the glue::glue() function, you actually need to double the backslashes again, turning \\s into \\\\s. This is because the glue::glue() function also interprets the backslash as an escape character, so the backslashes need to be escaped twice: once for the regular expression, and once for the glue::glue() function.

This works:
`glue::glue('My name is {stringr::str_extract("Jane, John", "(?=\\\\s).+")}')`

**Comment by jennybc** [comment]
Thanks @PettyCode!
