### ISSUE TITLE
Failed to evaluate glue component {label} Caused by error in vapply()

### ISSUE THREAD

**Issue by Steviey** [tidyverse/glue#323]
Can not identify anything... I don't use vapply()... Any ideas?
The message appears after rolling hundreds lines of code within a nesting. I have no clue where glue is used. It's not by me.

![image](https://github.com/tidyverse/glue/assets/3146082/861a9fa1-79d1-4ae3-8ee2-a04015b57185)

**Comment by jennybc** [comment]
Can you provide code that I can run to experience this? Otherwise, it's going to be hard to get traction here. 

---

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks!

**Comment by Steviey** [comment]
If I could, I would ;-), as I said hundreds of lines of code without any clue.

**Comment by hadley** [comment]
If you can't provide any hint to what you're doing, there's unfortunately not much we can do to help. And judging by the traceback, it seems most likely that the root error is in dplyr, not in glue.
