### ISSUE TITLE
Implement shell quoting transformer

### ISSUE THREAD

**Issue by flying-sheep** [tidyverse/glue#77]
Sometimes you can’t use `system2` to execute a command safely.

a shell transformer is nothing but the following, but is arguably more useful than `glue_sql`.

```r
shell_transformer <- function(type = c("sh", "csh", "cmd", "cmd2")) {
  function(code, envir) shQuote(glue::evaluate(code, envir), type)
}
```

**Comment by jimhester** [comment]
In general my intent is not to include transformers in the glue package itself. I added the `glue_sql()` and `glue_col()` transformers because they are both somewhat tricky to write correctly and in the SQL case a number of people were already using glue to write SQL queries.

I could add this transformer to the transformer vignette however.

**Comment by flying-sheep** [comment]
I think that would be good, as it demonstrates how simple transformers can be.
