### ISSUE TITLE
Distinguish between `NULL` and `character()`

### ISSUE THREAD

**Issue by jimhester** [tidyverse/glue#84]
e.g. so you don't have to have the else clause in something like the following

```r
arg <- 'foo'
required <- 1
actual <- 2
glue::glue("`{arg}` equals {required}", if (!is.null(actual)) "; not {actual}" else "")
```

**Comment by renkun-ken** [comment]
My use case is as follows:

```r
library(glue)

x <- -1

cat("x:", if (x > 0) "positive", "\n")
#> x:
str(glue("x: ", if (x > 0) "positive"))
#>  'glue' chr(0)
```

`NULL` is handled as length-0 vector in `glue`, which makes concatenate less consistent with how `cat()` handles `NULL`.

**Comment by euklid321** [comment]
Hi hi, given that this issue is quite old and the fact that glue::glue("someString{NULL}") returns chr(0) without warning is in my view quite dangerous and confusing, I wanted to ask if there are any considerations of implementing
https://github.com/tidyverse/design/issues/24#issuecomment-428558163
any time soon?

**Comment by dracodoc** [comment]
Today I get caught by this
> glue::glue("someString{NULL}") returns chr(0) without warning

I totally support to implement suggested feature, give error when something evaluate to NULL. I cannot think of a meaningful case of evaluate NULL to character(0). Be consistent with cat is not enough to justify the glue usage.

**Comment by dracodoc** [comment]
Further search found more users caught by this:

#100, #157 

Any plan to change current behavior to suggested [tidyverse/design#24 (comment) ](https://github.com/tidyverse/design/issues/24#issuecomment-428558163)?

The issue should be simple in implementation, just how the design choice is made.

**Comment by hadley** [comment]
@dracodoc it's very easy to see how the current behaviour causes problems. It is very difficult to tell the consequences of the changes — you can't tell where people currently rely on this behaviour because the code works. This means changing this behaviour will require careful thought and planning, and is not something we can do on a whim. We are aware of the problem, and likely to change the behaviour in the future, but agitating for change in this way is unlikely to make it happen any faster.

**Comment by dracodoc** [comment]
I'm sorry if my collection of related user cases gave the impression of a forceful demanding of change. I did try to make the voice louder, but didn't intend to be annoying.

On the other hand, wait more time (it has been 2 years) could have more users get caught off guard, or forced to change code to adapt to this behavior.

Anyway, this is not a really problem for me once I'm aware of this. Please take your time, thanks.

**Comment by dracodoc** [comment]
Thinking again, there is no need to make a choice here.The main reason that caught me and some users off guard is this behavior is unexpected and it took some time to find out.

Just raise a warning message will be enough ffor user to identify the reason and adjust for it. A warning should has minimal impact on code that rely on this behavior.

**Comment by mnist91** [comment]
Another Option would be to to include an argument analogous to `.na` (e.g. `.null`) whose default (e.g. `NULL`) causes the old behaviour or inserts the given string otherwise. Any thoughts about this?

**Comment by jimhester** [comment]
@mnist91 yes I think an argument to control this behavior like you describe is the right solution.
