### ISSUE TITLE
Automatically format doubles

### ISSUE THREAD

**Issue by hadley** [tidyverse/glue#86]
```R
glue::glue("{1/3}")
#> 0.333333333333333
```

Would be nice if you got something with fewer digits (maybe respecting `getOptions("digits")`)?

**Comment by jimhester** [comment]
This happens because glue essentially does this right now

```r
as.character(eval(parse(text = "1/3")))
#> [1] "0.333333333333333"
```

I could have glue call `format()` instead of `as.character()`

```r
format(eval(parse(text = "1/3")))
#> [1] "0.3333333"
```

Which would help in that case, but would cause other issues in other cases, e.g.

```r
format(eval(parse(text = "c(1, 100, 1000)")))
#> [1] "   1" " 100" "1000"
```

Not sure what a good solution is, `format()` seems problematic though as it adds
whitespace even with character input.

```r
format(eval(parse(text = "as.character(c(1, 100, 1000))")))
#> [1] "1   " "100 " "1000"
```

**Comment by hadley** [comment]
What if you just called the new format wrapper when `!is.object(x) && is.double(x)` ?

**Comment by jimhester** [comment]
One alternative would be to call `format(trim = TRUE, justify = "none")` which
should turn off padding in all cases.

**Comment by hadley** [comment]
I haven't needed this in the last 5 years, so lets say it's not worth implementing 😄
